markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

collections:
  categories:
    output: true
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
